### ISSUE TITLE
Error during provision

### ISSUE THREAD

**Issue by denys281** [joebew42/diaspora-replica#10]
During ```vagrant up development``` have error:

==> development: Fetched 4,025 kB in 213503982334601d 6h 56min 29s (0 B/s)
==> development: Reading package lists...
==> development: Running provisioner: puppet...
==> development: Running Puppet with site.pp...
==> development: stdin: is not a tty
==> development: Error: Could not parse application options: invalid option: --manifestdir
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by joebew42** [comment]
What version of `vagrant` are you using ? I recommend to install the latest available at [vagrantup](http://www.vagrantup.com).

**Comment by denys281** [comment]
@joebew42  Latest vagrant (1.7.4).

Same error as in one issue on vagrant https://github.com/mitchellh/vagrant/issues/3740 .

Can you reproduce this error? I think you need vagrant destroy and then vagrant up.

**Comment by joebew42** [comment]
I'm using vagrant 1.7.4, the same version you are using and the latest one. I am not able to reproduce this error. Trying a `vagrant destroy` and a `vagrant up` is the first thing that I've done when I read this issue and everything works fine.

I think the issue depends on the latest update of the box [Ubuntu 14.04 by puppetlabs](https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-14.04-64-puppet), I'll try to remove the local box and re-downloading this new one, I'm pretty sure the error will come up! Maybe they decided to update the version of puppet bundled on it.

**Comment by joebew42** [comment]
The problem was caused by the newer version of puppet (4.x) bundled within the updated box of puppetlabs. To keep these compatibility issues away I've decided to use the `vagrant-puppet-install` plugin in order to install a specific version of puppet during the provision.

So, consider to upgrade diaspora*-replica:

```
$ git pull origin master
$ git submodule update
$ vagrant plugin install vagrant-puppet-install
```

**Comment by denys281** [comment]
@joebew42  it works, thank you!
