### ISSUE TITLE
Possible fix for readme needed

### ISSUE THREAD

**Issue by denys281** [joebew42/diaspora-replica#11]
In chapter "How to set up a Development Environment"

After command: ```vagrant@development:~$ bundle install --with mysql postgresql``` I had an error "The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'". So before this I must execute ```gem install bundler```. Maybe we should add it to readme. And I'm not sure if this is issue or it happened only  in my case.

**Comment by joebew42** [comment]
Thank you! I've updated the `README.md`
