### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by denys281** [joebew42/diaspora-replica#13]
Today I start diaspora with vagrant and performance was bad.  In nginix log lot of time took assets, something like this I saw:

```
192.168.11.1 - - [02/Aug/2015:13:40:38 -0700] "GET /assets/app/views/aspect_membership_view.js?body=1 HTTP/1.1" 304 0 "http://development.diaspora.local/stream" "Mozilla/5.0 (Mac
intosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
192.168.11.1 - - [02/Aug/2015:13:40:38 -0700] "GET /assets/app/views/aspects_list_view.js?body=1 HTTP/1.1" 304 0 "http://development.diaspora.local/stream" "Mozilla/5.0 (Macintos
h; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
192.168.11.1 - - [02/Aug/2015:13:40:38 -0700] "GET /assets/app/collections/comments.js?body=1 HTTP/1.1" 304 0 "http://development.diaspora.local/stream" "Mozilla/5.0 (Macintosh;
Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
192.168.11.1 - - [02/Aug/2015:13:40:38 -0700] "GET /assets/app/views/comment_view.js?body=1 HTTP/1.1" 304 0 "http://development.diaspora.local/stream" "Mozilla/5.0 (Macintosh; In
tel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
```

And it tale long long time. /steam page loaded maybe 2 minutes.

Then I execute

```
rake assets:precompile
```

But it didn't help, maybe it all because of digest that we have near assets.

I also used this great article https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck (increase memory and cpus) but it didn't help.

But then I change nfs to rsync and all works much faster.  http://docs.vagrantup.com/v2/synced-folders/rsync.html 

I think this case needed to be instigated.

**Comment by joebew42** [comment]
Hi Denys,

I already noted time ago that diaspora in development mode is very slow. I think that these topics is a matter of the application itself and not of diaspora-replica. Tools like vagrant/puppet can help to setup a development environment and understand how to optimize the application. But, later, performance issues must be investigated and reported to [diaspora*](https://github.com/diaspora/diaspora).

However, I'll try to investigate and in case I find some useful information in order speed-up diaspora in development mode I'll update the README.md. If you've already tried something successfully, a pull-request is welcome :smile:
