### ISSUE TITLE
Why do we link diaspora_src?

### ISSUE THREAD

**Issue by cmrd-senya** [joebew42/diaspora-replica#15]
We mount the diaspora source code on the host machine by [this](https://github.com/joebew42/diaspora-replica/blob/master/Vagrantfile#L34).

However, what Capistrano deploys in the [development stage](https://github.com/joebew42/diaspora-replica/blob/master/capistrano/config/deploy/development.rb#L3-L4) is still the [upstream](https://github.com/diaspora/diaspora) repository develop branch.

Why not point Capistrano to the local repository? The best approach for the development would be if the current is also pointed on the mounted sources, so any changes in the original repository are reflected immediately. Otherwise, the development stage of the diaspora-replica is not very useful  - it can't be easily used for development purposes, since it would require too many manual steps for each change to test.

**Comment by joebew42** [comment]
Yes, exactly. The capistrano deployment process in development environment is only meant for testing purpose (I want to know if deployment works) and not for development.

The *diaspora_src* directory in the development machine is mounted directly from our host machine, where we store the source code of diaspora. So, we can work in our host machine and the changes are reflected in the guest machine.

I tried to describe the development workflow [here](https://github.com/joebew42/diaspora-replica#how-to-set-up-a-development-environment)

**Comment by cmrd-senya** [comment]
Ok, I see, thank you for your explanation!
