### ISSUE TITLE
Use ruby 2.1.6 instead of 2.1.5

### ISSUE THREAD

**Issue by joebew42** [joebew42/diaspora-replica#6]
The latest ruby 2.1 is the 2.1.6. The file site.pp should be updated.

**Comment by joebew42** [comment]
Closed by: https://github.com/joebew42/diaspora-replica/commit/0d5a4db1d2db64bdd296d5ab0a11bca78363f799

**Comment by Flaburgan** [comment]
With diaspora* 0.6 the recommended version of Ruby is 2.3 ;)

**Comment by joebew42** [comment]
@Flaburgan yeah, bumped at 2.3 :+1:
