### ISSUE TITLE
failing test for photo EXIF data

### ISSUE THREAD

**Issue by zaziemo** [joebew42/diaspora-replica#8]
bin/rspec spec/models/photo_spec.rb:162 fails with the following error message: https://gist.github.com/Realtin/bc21c95e0cfcbf23a886

Since no one else seems to have this test failing, probably it has something to do with my dev environment setup?
I am running the tests in a vagrant environment installed via 
https://wiki.diasporafoundation.org/Installation/Vagrant_puppet_capistrano#How_to_set_up_a_Development_Environment

**Comment by joebew42** [comment]
Yes I can confirm, I'm investigating this issue right now. I'm comparing the [TravisCI](https://travis-ci.org/diaspora/diaspora) build steps and its seems ok. Maybe we are missing something or we have some dirty files that have to be deleted somewhere. I don't know exactly, I am not a diaspora expert :/

**Comment by Realtin** [comment]
yep, we use branch ``develop``

**Comment by joebew42** [comment]
@zaziemo @Realtin It seems that the problem is caused by some Read/Write issue of the virtualbox shared folder, I switched and updated the Vagrantfile in order to use the NFS and now test pass.
